"""
Django settings for projectmanage project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'egkavr&kh%xnci6+#r@_s@*c)p3a)_y3(f$@mehy2%4&bl9pp5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'projectmanageapp',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'projectmanage.urls'

# APP_DIR=os.path.dirname( globals()['__file__'] )
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert your TEMPLATE_DIRS here
            'projectmanageapp/templates/',
            # C://Users/msun.sun/Desktop/projectmanage/
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectmanage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DBNAME = 'projectmanager'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
APP_PATH=os.path.abspath(os.path.dirname(__file__)).replace('\\','/')
STATIC_PATH =os.path.join(APP_PATH,'static').replace('\\','/')
STATIC_ROOT = ''
# STATICFILES_DIRS = (
#     os.path.join(APP_PATH, "static"),
# )
STATICFILES_DIRS = ('',
    (os.path.join(STATIC_PATH,'css').replace('\\','/')),
    # os.path.join(STATIC_ROOT,'css').replace('\\','/'),
    # os.path.join(STATIC_ROOT,'js').replace('\\','/'),
    # os.path.join(STATIC_ROOT,'images').replace('\\','/'),
)
STATIC_URL = '/static/'

MEDIA_ROOT = 'D:\djangogit\django\projectmanage\projectmanageapp\media'
MEDIA_URL = '/media/'